# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

builders:
  merge_json_builder:
    import: package:stratos/builder.dart
    builder_factories: [mergeJsonBuilder]
    build_extensions: {'.base.json': ['.json']}
    auto_apply: root_package
targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        options:
          compiler: dart2js
          dart2js_args:
            - --csp
